version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas.bitcoin-studio.com

functions:
  bitcoin-studio:
    lang: dockerfile${DEV}
    handler: ./function
    image: janakasteph/bitcoin-studio:${DEV:-latest}