version: 1.0
provider:
  name: openfaas
  #gateway: https://openfaas.rogue-paprika.top
  #gateway: https://openfaas-ingress-janaka-steph.cloud.okteto.net
  gateway: http://127.0.0.1:8080
functions:
  bitcoin-studio-client:
    lang: dockerfile
    handler: ./client
    image: janakasteph/bitcoin-studio-client
    #image: registry.cloud.okteto.net/janaka-steph/bitcoin-studio-client:dev
    #image: registry.cloud.okteto.net/janaka-steph/bitcoin-studio-client:latest
    environment:
      write_debug: true