apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-studio-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-studio-server
  template:
    metadata:
      labels:
        app: bitcoin-studio-server
    spec:
      containers:
        - name: bitcoin-studio-server
          image: janakasteph/bitcoin-studio-server
          ports:
            - containerPort: 5000
          env:
            - name: SMTP_GMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: smtp-gmail-pass
                  key: SMTP_GMAIL_PASS