version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ../api
    volumes:
      - /app/node_modules
      - ../api:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    volumes:
      - /app/node_modules
      - ../client:/app
  nginx:
    depends_on:
      - 'client'
      - 'api'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx-dev
    ports:
      - '3050:80'