# Global Ingress-Nginx configuration - HTTP Headers
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: default
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: "1; mode=block"
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin