apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: www-bitcoin-studio-staging
  namespace: openfaas
  annotations:
spec:
  domain: "www.bitcoin-studio.com"
  function: "bitcoin-studio-client"
  ingressType: "nginx"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-staging"
      kind: "Issuer"
