apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: www-bitcoin-studio
  namespace: openfaas
spec:
  domain: "www.bitcoin-studio.com"
  function: "bitcoin-studio"
  ingressType: "nginx"
  path: ""
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-prod"
      kind: "Issuer"
