# For HTTPS Local Dev
# After applying the Issuer, the ss certificate has to be trusted by the OS
# https://callbackinsanity.com/trusting-development-stating-fake-ssl-certificates-on-osx

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: openfaas
spec:
  selfSigned: {}