apiVersion: openfaas.com/v1alpha2
kind: FunctionIngress
metadata:
  name: www-bitcoin-studio-staging
  namespace: openfaas
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = "bitcoin-studio.com") {
          return 308 https://www.bitcoin-studio.com$request_uri;
      }
spec:
  domain: "www.bitcoin-studio.com"
  function: "bitcoin-studio-client"
  ingressType: "nginx"
  tls:
    enabled: true
    issuerRef:
      name: "letsencrypt-staging"
      kind: "Issuer"
