name: Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      # NPM
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: NPM install
        run: npm install
        working-directory: ./function

      #- name: NPM run test
      #  run: npm run test
      #  working-directory: ./function

      - name: NPM run lint
        run: npm run lint
        working-directory: ./function

      - name: NPM audit
        uses: oke-py/npm-audit-action@v1.4.0
        with:
          audit_level: moderate
          github_token: ${{secrets.GITHUB_TOKEN}}
          issue_assignees: Janaka-Steph
          issue_labels: vulnerability,test
          working_directory: ./function

      - name: NPM run build
        run: npm run build
        working-directory: ./function

      - name: Create OpenFaaS bundle
        uses: LucasRoesler/openfaas-action/shrinkwrap@v0.1.0
        with:
          tag: latest
          path: stack.yml

      - name: Build and push to Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: janakasteph/bitcoin-studio
          tags: latest
          path: build/bitcoin-studio