name: CI

on: 
  push:
    branches:
      - openfaas-nginx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Fetch Template
      uses: LucasRoesler/openfaas-action/template_store_pull@v0.1.0
      with:
        name: "dockerfile"
    - name: Build
      uses: LucasRoesler/openfaas-action/build@v0.1.0
    - name: Push image
      uses: LucasRoesler/openfaas-action/push@v0.1.0
      if: "success() && github.ref == 'refs/heads/openfaas-nginx' "
